### ISSUE TITLE
When i use my own settings to middle click, edit do not work.

### ISSUE THREAD

**Issue by broken1arrow** [DutchJelly/CraftEnhance#11]
All plugin i come pass, has no issue where i set in client of minecraft.I use middelclick on a side button (its much better an scroll wheel). 

And no plugin i counter has accept if i use different buttons. Try on paper-79 (1.16.1). 

No error in console, if i use debug, i cant tell differences if i use scroll wheel or my button (some are button 4 in minecraft). But i show both i use, only with scroll wheel i get edit menu (i hope i don't need hack so i can use the button I want).
https://pastebin.com/sixT5B4p

And if i reload the plugin i get 
[09:34:06] [Server thread/ERROR]: Tried to load unrecognized recipe: craftenhance:cehrecipelink5 removed now. on every reload (and client have to relog to see his recipe again). On server start i not get this error.

**Comment by DutchJelly** [comment]
This issue is related to a spigot issue with the `pick a block key` not properly relating to the clicktype of `MIDDLE_CLICK`. I also added right click support for opening the editor to resolve this.

**Comment by broken1arrow** [comment]
Items
https://pastebin.com/TZS4z7Uv
Recipe
https://pastebin.com/xW3XrdCP

**Comment by broken1arrow** [comment]
It has with new update change behavior, reload remove recipe and only way to get it back is rejoin (he can use recipe, but not show in the green book). When player rejoin the error come up (and recipe come back to the green book).

**Comment by DutchJelly** [comment]
The players can learn recipes on join, this fixes the problem. However, the knowledge book isn't really supporting item meta eitherway, so this can only be supported when some knowledgebook click event would get added to Spigot.
