### ISSUE TITLE
Enabling error

### ISSUE THREAD

**Issue by itsTurnip** [DutchJelly/CraftEnhance#2]
Hi!

I'm getting this errors while starting server. Here's my [latest.log](https://gist.github.com/itsTurnip/51e48c7b028a3e2b2a9f4e380e599a45#file-latest-log-L370), [config.yml](https://gist.github.com/itsTurnip/72435c3d74f774892b0f5fa0df42c711), [items.yml](https://gist.github.com/itsTurnip/422c0aca42221ced0dfdc3b2dc9ea8b8), [recipes.yml](https://gist.github.com/itsTurnip/cd2dae6b203f5342f129d5178d3fb70d)

**Comment by DutchJelly** [comment]
The issue had to do with the fact that empty spaces in inventories were previously not null items, but air. 
I resolved it by adding simple null checks in the InventoryClick handler functions in the GUI's.

Thanks for reporting the issue with the required logs so it was easy to find and resolve.
