### ISSUE TITLE
Recipe deserializing is sometimes not deserializing result item properly

### ISSUE THREAD

**Issue by DutchJelly** [DutchJelly/CraftEnhance#21]
There's a bug in the plugin that causes some items to not be deserialized properly, causing an `IllegalStateException` because a result item of a recipe cannot be null. This is generally harmless to servers, because the plugin will just skip the one recipe that's faulty.

**Comment by broken1arrow** [comment]
Can this help, it load my 9 recipe (it is 10 with KappaUnion recipe)
Recipe from KappaUnion

Recipe
https://pastebin.com/UW3JMqY5
Item
https://pastebin.com/vVTSj8Rg

https://pastebin.com/CEKmheK4

startup log
https://pastebin.com/n314Xq8f

**Comment by broken1arrow** [comment]
Hard to confirm if it is still a issue. But should be already solved as don't heard about issues for long time.
