### ISSUE TITLE
Permission showing 'null' in recipe editor.

### ISSUE THREAD

**Issue by DavidVioMC** [DutchJelly/CraftEnhance#28]
Permission show as `null` in recipe edior but they show fine in recipes.yml.

Unsure if this is a bug related to 2.4.2 because I updated from 2.3.3 to 2.4.2. The bug could be caused because of updating from 2.3.3 to 2.4.2.

![image](https://user-images.githubusercontent.com/40337710/97747103-54f25c80-1ae3-11eb-8a09-505b0e6ef245.png)

**Comment by DutchJelly** [comment]
This has been fixed in 2.4.3.
