### ISSUE TITLE
PaperMC server is throwing na issue during startup "to give their recipe a static key using NamespacedKey"

### ISSUE THREAD

**Issue by lemonka** [DutchJelly/CraftEnhance#29]
**Describe the bug**
 java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.

**To Reproduce**
1. Install plugin
2. Start server

**Show console logs**
 java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.

**Comment by DutchJelly** [comment]
Thank you for reporting this. It should be fixed in versions 2.4.2 and 2.4.3.
