### ISSUE TITLE
Not working on 1.14.4

### ISSUE THREAD

**Issue by YouHaveTrouble** [DutchJelly/CraftEnhance#3]
> [01:34:06] [Server thread/INFO]: [CraftEnhance] Enabling CraftEnhance v2.3.3
> [01:34:06] [Server thread/INFO]: [CraftEnhance] items.yml doesn't exist... creating it.
> [01:34:06] [Server thread/INFO]: [CraftEnhance] recipes.yml doesn't exist... creating it.
> [01:34:07] [Server thread/ERROR]: Error occurred while enabling CraftEnhance v2.3.3 (Is it up to date?)
> java.lang.NoSuchFieldError: STAINED_GLASS_PANE
> 	at com.dutchjelly.bukkitadapter.Adapter.GetStainedGlassPane(Adapter.java:57) ~[?:?]
> 	at com.dutchjelly.craftenhance.Util.GUIButtons.init(GUIButtons.java:29) ~[?:?]
> 	at com.dutchjelly.craftenhance.CraftEnhance.onEnable(CraftEnhance.java:58) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Paper-154]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[server.jar:git-Paper-154]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[server.jar:git-Paper-154]
> 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[server.jar:git-Paper-154]
> 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[server.jar:git-Paper-154]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[server.jar:git-Paper-154]
> 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[server.jar:git-Paper-154]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[server.jar:git-Paper-154]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
> [01:34:07] [Server thread/INFO]: [CraftEnhance] Disabling CraftEnhance v2.3.3
> [01:34:07] [Server thread/ERROR]: Error occurred while disabling CraftEnhance v2.3.3 (Is it up to date?)
> java.lang.NullPointerException: null
> 	at com.dutchjelly.craftenhance.CraftEnhance.onDisable(CraftEnhance.java:74) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[server.jar:git-Paper-154]
> 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[server.jar:git-Paper-154]
> 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[server.jar:git-Paper-154]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:git-Paper-154]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[server.jar:git-Paper-154]
> 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[server.jar:git-Paper-154]
> 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[server.jar:git-Paper-154]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[server.jar:git-Paper-154]
> 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[server.jar:git-Paper-154]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[server.jar:git-Paper-154]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by DutchJelly** [comment]
Just to make sure, you're using this version right? 
![image](https://user-images.githubusercontent.com/20456306/63224112-d0f2d400-c1bf-11e9-9b0f-f733f35be013.png)

**Comment by YouHaveTrouble** [comment]
Yes, the 1.14 one.

**Comment by DutchJelly** [comment]
Add me on Discord so I can maybe resolve and debug this better. DutchJelly#2301
