### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by hkkongou** [DutchJelly/CraftEnhance#31]
**Describe the bug**
Place an item to inventory crafting slot, will show red error message
ceh 2.4.2 
paper 457 1.16.5
**To Reproduce**
1. put item to crafting slot
2. red error message shows in console
![image](https://user-images.githubusercontent.com/61608872/106375405-ac47e780-63c6-11eb-9900-2c1037348982.png)

**Show console logs**
Please show the startup logs and logs of the error itself. Pastebin.com is a nice site that allows you to paste large console errors.
![image](https://user-images.githubusercontent.com/61608872/106375392-8de1ec00-63c6-11eb-9ec4-6dcfedadf7a8.png)

**[optional] add items.yml and recipes.yml**
To reproduce the bug, it could be helpful to see the items and recipes that you're using. Decide yourself if you want to provide this.

[items.txt](https://github.com/DutchJelly/CraftEnhance/files/5899216/items.txt)
[recipes.txt](https://github.com/DutchJelly/CraftEnhance/files/5899217/recipes.txt)

**Comment by DutchJelly** [comment]
First of all, thanks for reporting this bug. 

I would also like to know if this causes any critical issues like duping. If that's the case I am going to fix this immediately.

**Comment by hkkongou** [comment]
no major problem, just error message appear so far

**Comment by DutchJelly** [comment]
I have not closed this issue, even though it seems to be fixed. Sorry for not handling your issue professionally.
