### ISSUE TITLE
Can't Disable Recipes After Plugin Reload

### ISSUE THREAD

**Issue by trafoziya** [DutchJelly/CraftEnhance#33]
I installed the plugin today and try disabling some recipes. It works perfect and disables everything that i click. But when i add recipes and try reloading the plugin, /ceh disable gui get removed. By removed i mean, all the items that i can click to disable is gone. Other gui elements like next page and recipe enable button are still there. It fixes when i completely restart server. I tried reproducing it like i said and it keep removing all the items from the gui. 

**To Reproduce**
1. Use /ceh disable to check if the gui works
2. If gui works, disable some recipes
3. Use /ceh reload
4. Check disabler gui

**Show console logs**
There isnt an error on console or logs

**Comment by DutchJelly** [comment]
This'll be fixed in version 2.4.3. Thanks for reporting this.
