### ISSUE TITLE
recipie making fails 

### ISSUE THREAD

**Issue by hellfiregp** [DutchJelly/CraftEnhance#38]
**Describe the bug**
hi i have a minehut server i tried to make op gear and compact netherit 4 my server but all recipies i mad messed up and some didnt create 4 (3 with 9 variants) wasnt created but 5 was but they were wrong
**To Reproduce**
1.join a minhutserver with the plugin
1,5. perform command '/ceh createrecipie and make a recipie'
2. Click on 'save'
3. then /recipies
4. click on recipie

**Show console logs**
Please show the startup logs and logs of the error itself. Pastebin.com is a nice site that allows you to paste large console errors.
cant get log
**[optional] add items.yml and recipes.yml**
To reproduce the bug, it could be helpful to see the items and recipes that you're using. Decide yourself if you want to provide this.

**Comment by DutchJelly** [comment]
Minehut often uses an older version of the plugin. What version of CEH are you using?

**Comment by hellfiregp** [comment]
i dont play on minehut anymore


Den mån 13 dec. 2021 kl 13:36 skrev Jelle ***@***.***>:

**Comment by broken1arrow** [comment]
> **Describe the bug** A clear and concise description of what the bug is. hi i have a minehut server i tried to make op gear and compact netherit 4 my server but all recipies i mad messed up and some didnt create 4 (3 with 9 variants) wasnt created but 5 was but they were wrong **To Reproduce** Steps to reproduce the behavior: 1.join a minhutserver with the plugin 1,5. perform command '/ceh createrecipie and make a recipie' 2. Click on 'save' 3. then /recipies 4. click on recipie
> 
> **Show console logs** Please show the startup logs and logs of the error itself. Pastebin.com is a nice site that allows you to paste large console errors. cant get log **[optional] add items.yml and recipes.yml** To reproduce the bug, it could be helpful to see the items and recipes that you're using. Decide yourself if you want to provide this.

This is fixed in 2.4.4.x versions. So recommend nu use the minehut version, is old and buggy version (you can add custom plugins on minehut also).
