### ISSUE TITLE
request

### ISSUE THREAD

**Issue by AlexNova1555** [DutchJelly/CraftEnhance#4]
can you please add a reload command for the plugin?
i really need it!
and how do i edit recipe after i have saved it?

**Comment by DutchJelly** [comment]
I'll add a reload function to the plugin! Thanks for the suggestion.

And to answer your second question: If you go to the recipe-viewer (using ``/recipes``) you can simply click on recipes with the mouse wheel button to open the editor. For this you do need ceh.edit permissions by default.
