### ISSUE TITLE
Recipes: "Match Meta" changes to "Only Match Type" on reload

### ISSUE THREAD

**Issue by Erizofrenia** [DutchJelly/CraftEnhance#40]
I have multiple recipes in my server and all of those has match meta, but when i restart or /reload they all change to only match type again. I´m using CraftEnhance 2.4.1 in Minecraft 1.12.2

**To Reproduce**
1. Create recipes
2. Activate Match Meta in all my recipes
3. They work well
4. Restart server or reload plugin
5. All my recipes return to only match type 

[recipes.txt](https://github.com/DutchJelly/CraftEnhance/files/7479462/recipes.txt)
[items.txt](https://github.com/DutchJelly/CraftEnhance/files/7479463/items.txt)

https://pastebin.com/SiaJkN4S

**Comment by DutchJelly** [comment]
This is fixed in version 2.4.3.
