### ISSUE TITLE
Craft don't work after stop ,save backup and restart.

### ISSUE THREAD

**Issue by charlyg31** [DutchJelly/CraftEnhance#44]
**Describe the bug**

Hello, at 6:00 am, I stop my server, I save on other server backup and restart the server.
All craft don't work. I need to reload the plugins for work.

**To Reproduce**
1. perform command '...'

**Show console logs**
Please show the startup logs and logs of the error itself. Pastebin.com is a nice site that allows you to paste large console errors.

I don't have error on console.

**[optional] add items.yml and recipes.yml**
To reproduce the bug, it could be helpful to see the items and recipes that you're using. Decide yourself if you want to provide this.

Items.yml: https://pastebin.com/Hg3BnkXG
Recipes.yml: https://pastebin.com/imUSUn61

I already had the bug in the previous version.

**Comment by charlyg31** [comment]
I find the problems, craft don't work after commande, /Minecraft:reload

**Comment by broken1arrow** [comment]
> I find the problems, craft don't work after commande, /Minecraft:reload

not recommended use any type of reload, if it not /pluginname reload. For example /reload confirm should not be used. Should ether way work better with the 2.5.0 update.

**Comment by broken1arrow** [comment]
This issue can be closed
