### ISSUE TITLE
NBT Problem

### ISSUE THREAD

**Issue by XionioXMaster** [DutchJelly/CraftEnhance#46]
The plugin does not take into account other items with model-data and cannot adequately display the craft
![image](https://user-images.githubusercontent.com/86433158/201478936-03445ee4-9335-4192-93d2-35a66ddb9734.png)
![image](https://user-images.githubusercontent.com/86433158/201478950-139fc8a7-b7cf-4cc7-98a8-6301de851a43.png)

**Comment by broken1arrow** [comment]
If your ingredients has metadata and you have learn-recipe true. 

It is a limit in spigot api. we can't add recipe to player with metadata as ingredients. Only way is use nms (and that create new problems).
