### ISSUE TITLE
Crafts do not match what you selected as match

### ISSUE THREAD

**Issue by blikies** [DutchJelly/CraftEnhance#48]
[](url)**Describe the bug**
I selected match name and lore but the it can be crafted from a different item

**To Reproduce**
Set up a recipe on match name and lore (netherbricks) 
then use a name, and tryt it with an netherbrick without a name

**Show console logs**

**Comment by broken1arrow** [comment]
> 

Do you use version 2.5.7 or later?

Do you used a named item in your custom recipe?

**Comment by broken1arrow** [comment]
> **Describe the bug** I selected match name and lore but the it can be crafted from a different item
> 
> **To Reproduce** Set up a recipe on match name and lore (netherbricks) then use a name, and tryt it with an netherbrick without a name
> 
> **Show console logs**

Do you use version 2.5.7 or later? Do you used a named item in your custom recipe?

**Comment by broken1arrow** [comment]
> **Describe the bug** I selected match name and lore but the it can be crafted from a different item
> 
> **To Reproduce** Set up a recipe on match name and lore (netherbricks) then use a name, and tryt it with an netherbrick without a name
> 
> **Show console logs**

I try with this command /give @p nether_brick{display:{Name:'[{"text":"","italic":false}]'}} 1 and /give @p nether_brick{display:{Name:'[{"text":"test","italic":false}]'}} 1 and add the netherbricks as ingredients. Below can you download my test examples. 

The version I use should not differ from spigot on this point, but try the newest version I will soon upload on spigot. 


[recips.zip](https://github.com/DutchJelly/CraftEnhance/files/11749134/recips.zip)

**Comment by broken1arrow** [comment]
Alright this also fixed
