### ISSUE TITLE
No source code updates?

### ISSUE THREAD

**Issue by flleeppyy** [DutchJelly/CraftEnhance#49]
Spigot's site shows numerous updates, but the source code repo has none? When are you going to push the source again?

**Comment by stateisbad** [comment]
This is also important to me. :+1:

**Comment by DutchJelly** [comment]
The plugin is now managed by BrokenArrow. Any updates are bugfixes or compatibility fixes, so the source code should still be valid. However, you could ask him on discord: https://discord.gg/8xYEbft

**Comment by broken1arrow** [comment]
> Spigot's site shows numerous updates, but the source code repo has none? When are you going to push the source again?

You have it here https://github.com/broken1arrow/CraftEnhance I fork the project and try keep it updated with the spigot version.
