### ISSUE TITLE
Get Could not pass event InventoryClickEvent (is new install)

### ISSUE THREAD

**Issue by broken1arrow** [DutchJelly/CraftEnhance#5]
I have 
CMI
JetsHoppers
Lands 
Mobfarmmanger
Ohthedungon
Worldedit

(paper 87 1.15.2)

So middle click not work (i´m are OP). 
I have three recipe only, so i cant edit the recept

I cant find reload command, you say in other post you fix (I have a bug, new recipe not work, so i have to do server restart).

**Comment by DutchJelly** [comment]
Could you add a pastebin link with the exception to the issue?

**Comment by broken1arrow** [comment]
> 
> 
> Could you add a pastebin link with the exception to the issue?
Yes ofc
https://pastebin.com/rWiQuk76

**Comment by DutchJelly** [comment]
This should be fixed in ``1.4.0``, if not please open a new issue.
