### ISSUE TITLE
False Message for Newer Version

### ISSUE THREAD

**Issue by stateisbad** [DutchJelly/CraftEnhance#50]
**Describe the bug**
When running versions newer than 2.4.4 (2.5.6 in my case), a message is still shown to update to 2.4.4.

**To Reproduce**
1. Install plugin
2. View error in logs

**Show console logs**
```
[CraftEnhance] There's a new version (2.4.4) of the plugin available on https://www.spigotmc.org/resources/1-9-1-19-custom-recipes-and-crafting-craftenhance.65058/ or https://dev.bukkit.org/projects/craftenhance/files.
```

**Comment by broken1arrow** [comment]
I'm full aware of this bug. It depends on where it get the version from and I have to then change the link and something I not want to do.

**Comment by Tomology12** [comment]
i get the bug, using 1.20.2, and 2.5.9, and it thinks a new update is 2.4.4

**Comment by broken1arrow** [comment]
> i get the bug, using 1.20.2, and 2.5.9, and it thinks a new update is 2.4.4

Fixed in my fork https://www.spigotmc.org/resources/1-9-1-20-fork-custom-recipes-and-crafting-craftenhance.111998/  that also have better support for 1.20.x versions and some new functions.

**Comment by Tomology12** [comment]
what caused it? will dutchjelly update the plugin?

**Comment by Tomology12** [comment]
i probs will use urs now ty

**Comment by broken1arrow** [comment]
> what caused it? will dutchjelly update the plugin?

Only have been updated that plugin for a year(around that). But this spring due to spigot changes I realized this will not hold in long-term. 

So i afraid it will not be any more updates on he's (dutchjelly) version at least from me, but that depends if he will come back or not (don't hold your breath).

**Comment by broken1arrow** [comment]
> i probs will use urs now ty

yes, it is not a big shift, if you use 2.5.x before. It build on same source-code. But versions after 5.9 have some GUI changes + added 1 more function (more will come with time). When I have more time more things will be added, but right now I need to focus on the bugs currently reported.

**Comment by broken1arrow** [comment]
Should not be big issue any more
