### ISSUE TITLE
Typos in Log Messages

### ISSUE THREAD

**Issue by stateisbad** [DutchJelly/CraftEnhance#51]
**Describe the bug**
There are some typos in the logs messages.

**To Reproduce**
1. Install plugin
2. See typos in logs

**Show console logs**
```
[CraftEnhance] Is untested on never minecraft versions an 1.18.2
```

This is purely cosmetic, but while I was opening other Issues, I figured what the heck.

**Comment by broken1arrow** [comment]
> **Describe the bug** There are some typos in the logs messages.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Install plugin
> 
>     2. See typos in logs
> 
> 
> **Show console logs**
> 
> ```
> [CraftEnhance] Is untested on never minecraft versions an 1.18.2
> ```
> 
> This is purely cosmetic, but while I was opening other Issues, I figured what the heck.

can you give suggested change for the text? I think it should not give that message any more if you use 1.19.4 or lower (perhaps not the fix is out on spigot jet).

**Comment by DutchJelly** [comment]
I'd suggest something like: 
`Is untested on newer minecraft versions than 1.18.2`

**Comment by broken1arrow** [comment]
I can't find the message in version 2.5.x, I think it is either already changed or removed.

**Comment by broken1arrow** [comment]
Alright I think this also fixed.
