### ISSUE TITLE
java.lang.NoSuchFieldException: b and error on the crafting table

### ISSUE THREAD

**Issue by AxDevv** [DutchJelly/CraftEnhance#53]
**Describe the bug**
When I execute the /ceh viewer command, this error is displayed. then when I go to the craft table, it puts paper and doesn't take the customModelData 

**Show console logs**
https://pastebin.com/bVUgbLSa

![image](https://github.com/DutchJelly/CraftEnhance/assets/96068728/ebd38463-8ab1-40a9-9505-90880d9bd72f)
![image](https://github.com/DutchJelly/CraftEnhance/assets/96068728/b92da518-2c22-488b-ab48-e10eee5668b2)

**Comment by broken1arrow** [comment]
> **Describe the bug** When I execute the /ceh viewer command, this error is displayed. then when I go to the craft table, it puts paper and doesn't take the customModelData
> 
> **Show console logs** https://pastebin.com/bVUgbLSa
> 
> ![image](https://user-images.githubusercontent.com/96068728/246781587-ebd38463-8ab1-40a9-9505-90880d9bd72f.png) ![image](https://user-images.githubusercontent.com/96068728/246781679-b92da518-2c22-488b-ab48-e10eee5668b2.png)

Fixed version do you find here https://github.com/broken1arrow/CraftEnhance/release.

The custom model data, is a bug I could look in to. Can you provide the recipe.yml and item.yml?
