### ISSUE TITLE
Link not leading to issues page provided in the console

### ISSUE THREAD

**Issue by ghost** [DutchJelly/CraftEnhance#54]
**Describe the bug**
When clicking on the link in the console it adds a period "[CraftEnhance] If you find a bug in the plugin, please report it to https://github.com/DutchJelly/CraftEnhance/issues[.] Removing this period will result in the correct link "period in question is the one I put between the 2 brackets"

**To Reproduce**
1. Click the link you provided from your plugin that is in the console at server launch 

**[optional] add items.yml and recipes.yml**
You put an unneeded period at the end of the link which shows like this "[CraftEnhance] If you find a bug in the plugin, please report it to https://github.com/DutchJelly/CraftEnhance/issues." when it should show like this "[CraftEnhance] If you find a bug in the plugin, please report it to https://github.com/DutchJelly/CraftEnhance/issues"

Here is a gif of the issue for more clarity: https://i.imgur.com/nWsZrsL.gif

**Comment by broken1arrow** [comment]
> 



> **Describe the bug** When clicking on the link in the console it adds a period "[CraftEnhance] If you find a bug in the plugin, please report it to [https://github.com/DutchJelly/CraftEnhance/issues[.]](https://github.com/DutchJelly/CraftEnhance/issues%5B.%5D) Removing this period will result in the correct link "period in question is the one I put between the 2 brackets"
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Click the link you provided from your plugin that is in the console at server launch
> 
> 
> **[optional] add items.yml and recipes.yml** You put an unneeded period at the end of the link which shows like this "[CraftEnhance] If you find a bug in the plugin, please report it to https://github.com/DutchJelly/CraftEnhance/issues." when it should show like this "[CraftEnhance] If you find a bug in the plugin, please report it to https://github.com/DutchJelly/CraftEnhance/issues"
> 
> Here is a gif of the issue for more clarity: https://i.imgur.com/nWsZrsL.gif

Not much of a bug, but can address this in next version and to get the updated source check here https://github.com/broken1arrow/CraftEnhance/tree/2.5.0 

Fixed here https://github.com/broken1arrow/CraftEnhance/commit/728f084b6a398458a68f122606827c31d3d8e011
