### ISSUE TITLE
Plugin does not load

### ISSUE THREAD

**Issue by BellCocoa** [DutchJelly/CraftEnhance#58]
**Describe the bug**

**To Reproduce**
1. perform command '...'

**Show console logs**
Please show the startup logs and logs of the error itself. Pastebin.com is a nice site that allows you to paste large console errors.
https://pastebin.com/UUHAMM57
**[optional] add items.yml and recipes.yml**
To reproduce the bug, it could be helpful to see the items and recipes that you're using. Decide yourself if you want to provide this.

**Comment by broken1arrow** [comment]
Purpur is not officially supported. But when have time I can look in to that issue.

**Comment by broken1arrow** [comment]
No one else reports this issue.

So could be closed now.
