### ISSUE TITLE
Error in console and more

### ISSUE THREAD

**Issue by MrElvandar** [DutchJelly/CraftEnhance#59]
Describe the bug
Version Minecraft - 1.20.1
Core - Arclight (For mods and plugins)
After trying to enter any command, an error appears in the console. In some cases, it can be ignored, but when you try to delete a crafting recipe, it is deleted only in the menu, but it is still available in the game, even after restarting the server.

To Reproduce
1. perform command '/ceh viewer'
2. Click on 'Some category and try delete recipe'
3. See error

Show console logs
Please show the startup logs and logs of the error itself. Pastebin.com is a nice site that allows you to paste large console errors.
https://pastebin.com/tPb4uER5

[optional] add items.yml and recipes.yml
To reproduce the bug, it could be helpful to see the items and recipes that you're using. Decide yourself if you want to provide this.

**Comment by broken1arrow** [comment]
Don't know the version of the plugin you use, but should work in the latest.

**Comment by broken1arrow** [comment]
No response and just 1.20.1 or 1.20.0 should not been used at all.

So should be closed.
