### ISSUE TITLE
custom recipes cannot match another

### ISSUE THREAD

**Issue by 5eveNight** [DutchJelly/CraftEnhance#60]
maybe only i meet this bug
i use paper-1.20.1-196.jar and java 17 and CraftEnhance-2.5.9.2.

i create some recipes like below:
recipe 1：a normal coal add four diamond become a special coal （for example，type coal，named super coal，with some lores）
![image](https://github.com/DutchJelly/CraftEnhance/assets/62527407/d76d307c-1b7a-4045-aed6-0f572453d55e)

recipe 2：two special coal combine （shapeless） become another special coal （for example，type coal，named ultra coal，with some different lores）
![image](https://github.com/DutchJelly/CraftEnhance/assets/62527407/eef2b3ec-bd55-4c9e-ae4a-1fad86a2fc82)

then the bug comes 
when i drag two normal coal into crafttable，they could product ultra coal！
![image](https://github.com/DutchJelly/CraftEnhance/assets/62527407/ded19fbf-1e2e-420e-b9d6-37868dc23f8e)

yes，i try every matchtype: MATCH_NAME / MATCH_META / MATCH_MODELDATA_AND_TYPE / MATCH_NAME_LORE
and i try command /ceh reload，try restart the server
and i try gamemode creative or survival
all these are useless
i remembered that the first time after i create these recipes，they works well. 
maybe yesterday or the day before yesterday，i stop the server.
today i start the server，meet the bug.
waiting for your reply.

**Comment by 5eveNight** [comment]
oh sh*t
if i use CraftEnhance-2.5.9，all work perfect!
so there is a bug hide in CraftEnhance-2.5.9.2

**Comment by 5eveNight** [comment]
damn it.
after restart server, CraftEnhance-2.5.9 also has this bug

**Comment by 5eveNight** [comment]
ok i understand
CraftEnhance-2.5.9 only show the product, i CANNOT drag out the product from slot, and after cancel craft, second time will not show the product（work perfect）
CraftEnhance-2.5.9.2 show the product, and i CAN drag out the product into inventory, absolutely BUG.

**Comment by broken1arrow** [comment]
> ok i understand CraftEnhance-2.5.9 only show the product, i CANNOT drag out the product from slot, and after cancel craft, second time will not show the product（work perfect） CraftEnhance-2.5.9.2 show the product, and i CAN drag out the product into inventory, absolutely BUG.

Sorry for late replay, I don't think I have change the logic in crafting between 2.5.9 and 2.5.9.2. But you mean you can take the product from crafting table or the gui? 

Could you send a video about the issue?

**Comment by 5eveNight** [comment]
[自动回复]：来信已收到，我将会尽快给您回复

**Comment by broken1arrow** [comment]
Your first issue I could not recreate. I have others complain on same thing, but even on latest Minecraft version I have not yet get that bug.

**Comment by 5eveNight** [comment]
> > ok i understand CraftEnhance-2.5.9 only show the product, i CANNOT drag out the product from slot, and after cancel craft, second time will not show the product（work perfect） CraftEnhance-2.5.9.2 show the product, and i CAN drag out the product into inventory, absolutely BUG.
> 
> Sorry for late replay, I don't think I have change the logic in crafting between 2.5.9 and 2.5.9.2. But you mean you can take the product from crafting table or the gui?
> 
> Could you send a video about the issue?

sorry for reply you soooo late.
I reproduce the BUG by 2.5.9.3 plugin, and record a video about 16 MB , maybe it is not very good to upload the BUG video to youtube, so if you mind message me a email to receive the full video.
here the test：
JAVA 17；
paper-1.20.1-196.jar；
only 2 plugins：CraftEnhance-2.5.9.3.jar ，PlayerIntensify-2.1.2.jar（ RPG plugin for special coke）.


recipe 1：two special coke（green name） combine to one ultra coke（gold name），shapeless ，MATCH_MODELDATA_AND_TYPE
![R1-1](https://github.com/DutchJelly/CraftEnhance/assets/62527407/78082678-66fe-4cc3-ab16-3966ba6470c2)
![R1-2](https://github.com/DutchJelly/CraftEnhance/assets/62527407/587e9885-18a3-4bf2-bb43-3741a36a9261)
![R1-3](https://github.com/DutchJelly/CraftEnhance/assets/62527407/bf622cee-8bee-4b51-a01c-1f19e1184578)
recipe 2：one ultra coke decomposed into two special coke，shapeless ，MATCH_MODELDATA_AND_TYPE
![R2-1](https://github.com/DutchJelly/CraftEnhance/assets/62527407/a241b906-f9ee-4523-95a8-5240f6171613)
![R2-2](https://github.com/DutchJelly/CraftEnhance/assets/62527407/e9bd6e26-2f6d-420b-8b34-7a7de246832b)
![R2-3](https://github.com/DutchJelly/CraftEnhance/assets/62527407/f250c08f-5bb7-4c2f-bc21-89607c2192e9)


GIFs about BUG：
BUG 1: two normal coke combine to one ultra coke
![1 00_00_00-00_00_30](https://github.com/DutchJelly/CraftEnhance/assets/62527407/01859796-dde6-48ec-aca6-9611419a8a3b)
BUG 2: one normal coke decomposed into two special coke
![2 00_00_00-00_00_30](https://github.com/DutchJelly/CraftEnhance/assets/62527407/259e5cc8-20c4-4f3d-9a67-cead9e9ffe64)

**Comment by 5eveNight** [comment]
> > > ok i understand CraftEnhance-2.5.9 only show the product, i CANNOT drag out the product from slot, and after cancel craft, second time will not show the product（work perfect） CraftEnhance-2.5.9.2 show the product, and i CAN drag out the product into inventory, absolutely BUG.
> > 
> > 
> > Sorry for late replay, I don't think I have change the logic in crafting between 2.5.9 and 2.5.9.2. But you mean you can take the product from crafting table or the gui?
> > Could you send a video about the issue?
> 
> sorry for reply you soooo late. I reproduce the BUG by 2.5.9.3 plugin, and record a video about 16 MB , maybe it is not very good to upload the BUG video to youtube, so if you mind message me a email to receive the full video. here the test： JAVA 17； paper-1.20.1-196.jar； only 2 plugins：CraftEnhance-2.5.9.3.jar ，PlayerIntensify-2.1.2.jar（ RPG plugin for special coke）.
> 
> recipe 1：two special coke（green name） combine to one ultra coke（gold name），shapeless ，MATCH_MODELDATA_AND_TYPE ![R1-1](https://private-user-images.githubusercontent.com/62527407/286232029-78082678-66fe-4cc3-ab16-3966ba6470c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA5NTMsIm5iZiI6MTcwMTE3MDY1MywicGF0aCI6Ii82MjUyNzQwNy8yODYyMzIwMjktNzgwODI2NzgtNjZmZS00Y2MzLWFiMTYtMzk2NmJhNjQ3MGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNTE1NWUyYTRkOGRlNDc1NjM3MGI2MTZkNGM1MDUzODViNmZiMjNjMzFmYWQ5NWMzY2M2NmUxNDE3YjhiODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ffeXFgkTCCCNRyCzWIsCtPzhlFhwatTZl_gMsEpNkqI) ![R1-2](https://private-user-images.githubusercontent.com/62527407/286232037-587e9885-18a3-4bf2-bb43-3741a36a9261.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA5NTMsIm5iZiI6MTcwMTE3MDY1MywicGF0aCI6Ii82MjUyNzQwNy8yODYyMzIwMzctNTg3ZTk4ODUtMThhMy00YmYyLWJiNDMtMzc0MWEzNmE5MjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZmQxYWY0MGNhODcyZjBiOGRlMmYzOGQ2OTVlYTc5YmE2Y2IzODk5NzVjMGFmZDYyN2U2MDE2MmExZjVjNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UAnFZnmAREvcTcMZEMr_5vs67RG4xbHRh2tf4K3zoK0) ![R1-3](https://private-user-images.githubusercontent.com/62527407/286232042-bf622cee-8bee-4b51-a01c-1f19e1184578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA5NTMsIm5iZiI6MTcwMTE3MDY1MywicGF0aCI6Ii82MjUyNzQwNy8yODYyMzIwNDItYmY2MjJjZWUtOGJlZS00YjUxLWEwMWMtMWYxOWUxMTg0NTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZDU2ZTQ0Yjk4NjQ5Yjc2ZWFjOWE0YzdjOTkyNjU4MWVmM2M5OTMzN2U4NTcwZTY4OGEwZDdjMWY3ZGMyYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zWZcn7cx1gyCh3T2yoJ-IrN3mx9nXiskvwiF5NZq3jg) recipe 2：one ultra coke decomposed into two special coke，shapeless ，MATCH_MODELDATA_AND_TYPE ![R2-1](https://private-user-images.githubusercontent.com/62527407/286232415-a241b906-f9ee-4523-95a8-5240f6171613.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA5NTMsIm5iZiI6MTcwMTE3MDY1MywicGF0aCI6Ii82MjUyNzQwNy8yODYyMzI0MTUtYTI0MWI5MDYtZjllZS00NTIzLTk1YTgtNTI0MGY2MTcxNjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYTI0MWUxZDFmYWQzZGRkZjA2N2FjOWRiN2ExZmM2NjkzYjBhOTI1ZWFlYTQyMmFjNWFiNjRlNjBjZjI1NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aRUy-LDixf3bHvVxu3DM8rCMiWw6-Nyf4Gsvh3lahAE) ![R2-2](https://private-user-images.githubusercontent.com/62527407/286232423-e9bd6e26-2f6d-420b-8b34-7a7de246832b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA5NTMsIm5iZiI6MTcwMTE3MDY1MywicGF0aCI6Ii82MjUyNzQwNy8yODYyMzI0MjMtZTliZDZlMjYtMmY2ZC00MjBiLThiMzQtN2E3ZGUyNDY4MzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhODA2ZjdjZjAxMjg2MTY0YjFjZmUyYzFkYzJkMTgwMjVhZjAxMzI4NzNjMzI2NjlkZDA1YWU4Nzk1OGYwMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DyVNcvAWK0WMoajVLBgBH8v2OCJrGlIE_7J-td5OzgA) ![R2-3](https://private-user-images.githubusercontent.com/62527407/286232428-f250c08f-5bb7-4c2f-bc21-89607c2192e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA5NTMsIm5iZiI6MTcwMTE3MDY1MywicGF0aCI6Ii82MjUyNzQwNy8yODYyMzI0MjgtZjI1MGMwOGYtNWJiNy00YzJmLWJjMjEtODk2MDdjMjE5MmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZWQxZDYyY2ZjZDQ4YTA3NWUxNDI3NDI3YjU5Nzk2MjE2ODdkZjQ2ZmMwNGI1ZTBiZmRmMDNkN2I3OGFiMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hTNYUPqFnAlyfqwgBzQyjkoaJdBRDGv_xdibTuNn-v8)
> 
> GIFs about BUG： BUG 1: two normal coke combine to one ultra coke ![1 00_00_00-00_00_30](https://private-user-images.githubusercontent.com/62527407/286232812-01859796-dde6-48ec-aca6-9611419a8a3b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA5NTMsIm5iZiI6MTcwMTE3MDY1MywicGF0aCI6Ii82MjUyNzQwNy8yODYyMzI4MTItMDE4NTk3OTYtZGRlNi00OGVjLWFjYTYtOTYxMTQxOWE4YTNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMWI5NDMwZjYwNWRkMGQ1Njg2OWQ3NWVhMTEyMzJkZTQ0YWQ0ZDhkYTM2NjBlN2RiNjg4YTUwMWIxMTFiYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hApY05RiHtRU_95Momk8UM_Cf3SX2Wgq71RZApWuCK4) [ ![1 00_00_00-00_00_30](https://private-user-images.githubusercontent.com/62527407/286232812-01859796-dde6-48ec-aca6-9611419a8a3b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA5NTMsIm5iZiI6MTcwMTE3MDY1MywicGF0aCI6Ii82MjUyNzQwNy8yODYyMzI4MTItMDE4NTk3OTYtZGRlNi00OGVjLWFjYTYtOTYxMTQxOWE4YTNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMWI5NDMwZjYwNWRkMGQ1Njg2OWQ3NWVhMTEyMzJkZTQ0YWQ0ZDhkYTM2NjBlN2RiNjg4YTUwMWIxMTFiYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hApY05RiHtRU_95Momk8UM_Cf3SX2Wgq71RZApWuCK4) ](https://private-user-images.githubusercontent.com/62527407/286232812-01859796-dde6-48ec-aca6-9611419a8a3b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA5NTMsIm5iZiI6MTcwMTE3MDY1MywicGF0aCI6Ii82MjUyNzQwNy8yODYyMzI4MTItMDE4NTk3OTYtZGRlNi00OGVjLWFjYTYtOTYxMTQxOWE4YTNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMWI5NDMwZjYwNWRkMGQ1Njg2OWQ3NWVhMTEyMzJkZTQ0YWQ0ZDhkYTM2NjBlN2RiNjg4YTUwMWIxMTFiYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hApY05RiHtRU_95Momk8UM_Cf3SX2Wgq71RZApWuCK4) [ ](https://private-user-images.githubusercontent.com/62527407/286232812-01859796-dde6-48ec-aca6-9611419a8a3b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA5NTMsIm5iZiI6MTcwMTE3MDY1MywicGF0aCI6Ii82MjUyNzQwNy8yODYyMzI4MTItMDE4NTk3OTYtZGRlNi00OGVjLWFjYTYtOTYxMTQxOWE4YTNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMWI5NDMwZjYwNWRkMGQ1Njg2OWQ3NWVhMTEyMzJkZTQ0YWQ0ZDhkYTM2NjBlN2RiNjg4YTUwMWIxMTFiYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hApY05RiHtRU_95Momk8UM_Cf3SX2Wgq71RZApWuCK4) BUG 2: one normal coke decomposed into two special coke ![2 00_00_00-00_00_30](https://private-user-images.githubusercontent.com/62527407/286233034-259e5cc8-20c4-4f3d-9a67-cead9e9ffe64.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA5NTMsIm5iZiI6MTcwMTE3MDY1MywicGF0aCI6Ii82MjUyNzQwNy8yODYyMzMwMzQtMjU5ZTVjYzgtMjBjNC00ZjNkLTlhNjctY2VhZDllOWZmZTY0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxOWE4M2U2YjBmNTk1Y2Y3MTZlZGNkNjAzZjRhY2MwZmExYzA5MDcyMzQxOGFkZmYyYjc2MjVkMzU1N2FkZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jTYuCDAebv7dWC5J8Xe2kA_avfEgmxf_PI856j3vZcM) [ ![2 00_00_00-00_00_30](https://private-user-images.githubusercontent.com/62527407/286233034-259e5cc8-20c4-4f3d-9a67-cead9e9ffe64.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA5NTMsIm5iZiI6MTcwMTE3MDY1MywicGF0aCI6Ii82MjUyNzQwNy8yODYyMzMwMzQtMjU5ZTVjYzgtMjBjNC00ZjNkLTlhNjctY2VhZDllOWZmZTY0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxOWE4M2U2YjBmNTk1Y2Y3MTZlZGNkNjAzZjRhY2MwZmExYzA5MDcyMzQxOGFkZmYyYjc2MjVkMzU1N2FkZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jTYuCDAebv7dWC5J8Xe2kA_avfEgmxf_PI856j3vZcM) ](https://private-user-images.githubusercontent.com/62527407/286233034-259e5cc8-20c4-4f3d-9a67-cead9e9ffe64.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA5NTMsIm5iZiI6MTcwMTE3MDY1MywicGF0aCI6Ii82MjUyNzQwNy8yODYyMzMwMzQtMjU5ZTVjYzgtMjBjNC00ZjNkLTlhNjctY2VhZDllOWZmZTY0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxOWE4M2U2YjBmNTk1Y2Y3MTZlZGNkNjAzZjRhY2MwZmExYzA5MDcyMzQxOGFkZmYyYjc2MjVkMzU1N2FkZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jTYuCDAebv7dWC5J8Xe2kA_avfEgmxf_PI856j3vZcM) [ ](https://private-user-images.githubusercontent.com/62527407/286233034-259e5cc8-20c4-4f3d-9a67-cead9e9ffe64.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA5NTMsIm5iZiI6MTcwMTE3MDY1MywicGF0aCI6Ii82MjUyNzQwNy8yODYyMzMwMzQtMjU5ZTVjYzgtMjBjNC00ZjNkLTlhNjctY2VhZDllOWZmZTY0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxOWE4M2U2YjBmNTk1Y2Y3MTZlZGNkNjAzZjRhY2MwZmExYzA5MDcyMzQxOGFkZmYyYjc2MjVkMzU1N2FkZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jTYuCDAebv7dWC5J8Xe2kA_avfEgmxf_PI856j3vZcM)

last time i try all kinds of MATCH，none works.
if i change back to 2.5.9, it works well.
but the GUI of 2.5.9 cannot change the set of any recipe（i click the button, but no response, i don't know why）
only i stop the server and change recipes.yml.

**Comment by 5eveNight** [comment]
last time i try all kinds of MATCH，none works.
if i change back to 2.5.9, it works well.
but the GUI of 2.5.9 cannot change the set of any recipe（i click the button, but no response, i don't know why）
only i stop the server and change recipes.yml.

**Comment by 5eveNight** [comment]
> last time i try all kinds of MATCH，none works. if i change back to 2.5.9, it works well. but the GUI of 2.5.9 cannot change the set of any recipe（i click the button, but no response, i don't know why） only i stop the server and change recipes.yml.

emmmmm
i restart the server, and change to MATCH_NAME_LORE.
2.5.9.3 works well.
maybe i made some mistakes last time

**Comment by broken1arrow** [comment]
> > last time i try all kinds of MATCH，none works. if i change back to 2.5.9, it works well. but the GUI of 2.5.9 cannot change the set of any recipe（i click the button, but no response, i don't know why） only i stop the server and change recipes.yml.
> 
> emmmmm i restart the server, and change to MATCH_NAME_LORE. 2.5.9.3 works well. maybe i made some mistakes last time

Match_meta should work also. But that mode is ok also.
