### ISSUE TITLE
plugin is repeatedly outputting "[CraftEnhance] [STDOUT] getServerRecipe shapelessfalse" to console? why. i think this is a bug, so i have put this here.

### ISSUE THREAD

**Issue by Tomology12** [DutchJelly/CraftEnhance#61]
**Describe the bug**
look at the name.

**To Reproduce**
use a minehut server on 1.20.2, with ceh 2.5.9, I just updated from 1.20.1, for which I downloaded the newest version of each plugin.
it didn't happen back when I was using 1.20.1.
I also get the bug of ceh thinking it should update to 2.4.4. (when its at 2.5.9)
[https://github.com/DutchJelly/CraftEnhance/issues/50](url)

**Show console logs**
Please show the startup logs and logs of the error itself. 
[console logs.txt](https://github.com/DutchJelly/CraftEnhance/files/13355196/console.logs.txt)

**[optional] add items.yml and recipes.yml**

[CraftEnhance.zip](https://github.com/DutchJelly/CraftEnhance/files/13355162/CraftEnhance.zip)
the plugin folder as a zip ^^

**Comment by broken1arrow** [comment]
yeah it is fixed in the latest version (or should be). Was not so easy find where that message was in the code :)
